/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTecnicosRouteImport } from './routes/_app.tecnicos'
import { Route as AppServicosRouteImport } from './routes/_app.servicos'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProdutosRouteImport } from './routes/_app.produtos'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppCronogramaRouteImport } from './routes/_app.cronograma'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppAprovacoesRouteImport } from './routes/_app.aprovacoes'
import { Route as AppOrdensIndexRouteImport } from './routes/_app.ordens.index'
import { Route as AppOrdensNovaRouteImport } from './routes/_app.ordens.nova'
import { Route as AppOrdensIdRouteImport } from './routes/_app.ordens.$id'
import { Route as AppAdminUsuariosRouteImport } from './routes/_app.admin.usuarios'
import { Route as AppAdminPermissoesRouteImport } from './routes/_app.admin.permissoes'
import { Route as AppAdminPerfisRouteImport } from './routes/_app.admin.perfis'
import { Route as AppAdminMenusRouteImport } from './routes/_app.admin.menus'
import { Route as AppAdminLogsRouteImport } from './routes/_app.admin.logs'
import { Route as AppAdminIaRouteImport } from './routes/_app.admin.ia'
import { Route as AppAdminDashboardUsuarioRouteImport } from './routes/_app.admin.dashboard-usuario'
import { Route as AppAdminDashboardPerfilRouteImport } from './routes/_app.admin.dashboard-perfil'
import { Route as AppAdminConfiguracoesSistemaRouteImport } from './routes/_app.admin.configuracoes-sistema'
import { Route as AppAdminBaseConhecimentoRouteImport } from './routes/_app.admin.base-conhecimento'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTecnicosRoute = AppTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramaRoute = AppCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIndexRoute = AppOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensNovaRoute = AppOrdensNovaRouteImport.update({
  id: '/ordens/nova',
  path: '/ordens/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPermissoesRoute = AppAdminPermissoesRouteImport.update({
  id: '/admin/permissoes',
  path: '/admin/permissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPerfisRoute = AppAdminPerfisRouteImport.update({
  id: '/admin/perfis',
  path: '/admin/perfis',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMenusRoute = AppAdminMenusRouteImport.update({
  id: '/admin/menus',
  path: '/admin/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIaRoute = AppAdminIaRouteImport.update({
  id: '/admin/ia',
  path: '/admin/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardUsuarioRoute =
  AppAdminDashboardUsuarioRouteImport.update({
    id: '/admin/dashboard-usuario',
    path: '/admin/dashboard-usuario',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminDashboardPerfilRoute = AppAdminDashboardPerfilRouteImport.update({
  id: '/admin/dashboard-perfil',
  path: '/admin/dashboard-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfiguracoesSistemaRoute =
  AppAdminConfiguracoesSistemaRouteImport.update({
    id: '/admin/configuracoes-sistema',
    path: '/admin/configuracoes-sistema',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminBaseConhecimentoRoute =
  AppAdminBaseConhecimentoRouteImport.update({
    id: '/admin/base-conhecimento',
    path: '/admin/base-conhecimento',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cronograma': typeof AppCronogramaRoute
  '/kanban': typeof AppKanbanRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/servicos': typeof AppServicosRoute
  '/tecnicos': typeof AppTecnicosRoute
  '/admin/base-conhecimento': typeof AppAdminBaseConhecimentoRoute
  '/admin/configuracoes-sistema': typeof AppAdminConfiguracoesSistemaRoute
  '/admin/dashboard-perfil': typeof AppAdminDashboardPerfilRoute
  '/admin/dashboard-usuario': typeof AppAdminDashboardUsuarioRoute
  '/admin/ia': typeof AppAdminIaRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/menus': typeof AppAdminMenusRoute
  '/admin/perfis': typeof AppAdminPerfisRoute
  '/admin/permissoes': typeof AppAdminPermissoesRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/ordens/nova': typeof AppOrdensNovaRoute
  '/ordens/': typeof AppOrdensIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cronograma': typeof AppCronogramaRoute
  '/kanban': typeof AppKanbanRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/servicos': typeof AppServicosRoute
  '/tecnicos': typeof AppTecnicosRoute
  '/': typeof AppIndexRoute
  '/admin/base-conhecimento': typeof AppAdminBaseConhecimentoRoute
  '/admin/configuracoes-sistema': typeof AppAdminConfiguracoesSistemaRoute
  '/admin/dashboard-perfil': typeof AppAdminDashboardPerfilRoute
  '/admin/dashboard-usuario': typeof AppAdminDashboardUsuarioRoute
  '/admin/ia': typeof AppAdminIaRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/menus': typeof AppAdminMenusRoute
  '/admin/perfis': typeof AppAdminPerfisRoute
  '/admin/permissoes': typeof AppAdminPermissoesRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/ordens/nova': typeof AppOrdensNovaRoute
  '/ordens': typeof AppOrdensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/aprovacoes': typeof AppAprovacoesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/cronograma': typeof AppCronogramaRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/servicos': typeof AppServicosRoute
  '/_app/tecnicos': typeof AppTecnicosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/base-conhecimento': typeof AppAdminBaseConhecimentoRoute
  '/_app/admin/configuracoes-sistema': typeof AppAdminConfiguracoesSistemaRoute
  '/_app/admin/dashboard-perfil': typeof AppAdminDashboardPerfilRoute
  '/_app/admin/dashboard-usuario': typeof AppAdminDashboardUsuarioRoute
  '/_app/admin/ia': typeof AppAdminIaRoute
  '/_app/admin/logs': typeof AppAdminLogsRoute
  '/_app/admin/menus': typeof AppAdminMenusRoute
  '/_app/admin/perfis': typeof AppAdminPerfisRoute
  '/_app/admin/permissoes': typeof AppAdminPermissoesRoute
  '/_app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/_app/ordens/$id': typeof AppOrdensIdRoute
  '/_app/ordens/nova': typeof AppOrdensNovaRoute
  '/_app/ordens/': typeof AppOrdensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aprovacoes'
    | '/clientes'
    | '/configuracoes'
    | '/cronograma'
    | '/kanban'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/tecnicos'
    | '/admin/base-conhecimento'
    | '/admin/configuracoes-sistema'
    | '/admin/dashboard-perfil'
    | '/admin/dashboard-usuario'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/menus'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/ordens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/aprovacoes'
    | '/clientes'
    | '/configuracoes'
    | '/cronograma'
    | '/kanban'
    | '/produtos'
    | '/relatorios'
    | '/servicos'
    | '/tecnicos'
    | '/'
    | '/admin/base-conhecimento'
    | '/admin/configuracoes-sistema'
    | '/admin/dashboard-perfil'
    | '/admin/dashboard-usuario'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/menus'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/ordens'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/aprovacoes'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/cronograma'
    | '/_app/kanban'
    | '/_app/produtos'
    | '/_app/relatorios'
    | '/_app/servicos'
    | '/_app/tecnicos'
    | '/_app/'
    | '/_app/admin/base-conhecimento'
    | '/_app/admin/configuracoes-sistema'
    | '/_app/admin/dashboard-perfil'
    | '/_app/admin/dashboard-usuario'
    | '/_app/admin/ia'
    | '/_app/admin/logs'
    | '/_app/admin/menus'
    | '/_app/admin/perfis'
    | '/_app/admin/permissoes'
    | '/_app/admin/usuarios'
    | '/_app/ordens/$id'
    | '/_app/ordens/nova'
    | '/_app/ordens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tecnicos': {
      id: '/_app/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof AppTecnicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cronograma': {
      id: '/_app/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AppCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aprovacoes': {
      id: '/_app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/': {
      id: '/_app/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AppOrdensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/nova': {
      id: '/_app/ordens/nova'
      path: '/ordens/nova'
      fullPath: '/ordens/nova'
      preLoaderRoute: typeof AppOrdensNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/usuarios': {
      id: '/_app/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/permissoes': {
      id: '/_app/admin/permissoes'
      path: '/admin/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AppAdminPermissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/perfis': {
      id: '/_app/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AppAdminPerfisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/menus': {
      id: '/_app/admin/menus'
      path: '/admin/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AppAdminMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/logs': {
      id: '/_app/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/ia': {
      id: '/_app/admin/ia'
      path: '/admin/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AppAdminIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard-usuario': {
      id: '/_app/admin/dashboard-usuario'
      path: '/admin/dashboard-usuario'
      fullPath: '/admin/dashboard-usuario'
      preLoaderRoute: typeof AppAdminDashboardUsuarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard-perfil': {
      id: '/_app/admin/dashboard-perfil'
      path: '/admin/dashboard-perfil'
      fullPath: '/admin/dashboard-perfil'
      preLoaderRoute: typeof AppAdminDashboardPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/configuracoes-sistema': {
      id: '/_app/admin/configuracoes-sistema'
      path: '/admin/configuracoes-sistema'
      fullPath: '/admin/configuracoes-sistema'
      preLoaderRoute: typeof AppAdminConfiguracoesSistemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/base-conhecimento': {
      id: '/_app/admin/base-conhecimento'
      path: '/admin/base-conhecimento'
      fullPath: '/admin/base-conhecimento'
      preLoaderRoute: typeof AppAdminBaseConhecimentoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCronogramaRoute: typeof AppCronogramaRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppServicosRoute: typeof AppServicosRoute
  AppTecnicosRoute: typeof AppTecnicosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminBaseConhecimentoRoute: typeof AppAdminBaseConhecimentoRoute
  AppAdminConfiguracoesSistemaRoute: typeof AppAdminConfiguracoesSistemaRoute
  AppAdminDashboardPerfilRoute: typeof AppAdminDashboardPerfilRoute
  AppAdminDashboardUsuarioRoute: typeof AppAdminDashboardUsuarioRoute
  AppAdminIaRoute: typeof AppAdminIaRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminMenusRoute: typeof AppAdminMenusRoute
  AppAdminPerfisRoute: typeof AppAdminPerfisRoute
  AppAdminPermissoesRoute: typeof AppAdminPermissoesRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppOrdensIdRoute: typeof AppOrdensIdRoute
  AppOrdensNovaRoute: typeof AppOrdensNovaRoute
  AppOrdensIndexRoute: typeof AppOrdensIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCronogramaRoute: AppCronogramaRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppServicosRoute: AppServicosRoute,
  AppTecnicosRoute: AppTecnicosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminBaseConhecimentoRoute: AppAdminBaseConhecimentoRoute,
  AppAdminConfiguracoesSistemaRoute: AppAdminConfiguracoesSistemaRoute,
  AppAdminDashboardPerfilRoute: AppAdminDashboardPerfilRoute,
  AppAdminDashboardUsuarioRoute: AppAdminDashboardUsuarioRoute,
  AppAdminIaRoute: AppAdminIaRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminMenusRoute: AppAdminMenusRoute,
  AppAdminPerfisRoute: AppAdminPerfisRoute,
  AppAdminPermissoesRoute: AppAdminPermissoesRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppOrdensIdRoute: AppOrdensIdRoute,
  AppOrdensNovaRoute: AppOrdensNovaRoute,
  AppOrdensIndexRoute: AppOrdensIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
